name       : tomlc99
version    : 20210518
release    : 1
source     :
    - git|https://github.com/cktan/tomlc99.git : d7dd697c35ead435733764c63d47f7cbf00b8fa9
license    : MIT
component  : programming.library
summary    : TOML 1.0 complaint library for c99
description: |
    TOML 1.0 complaint library for c99
build      : |
    %make
install    : |
    %make_install prefix=$installdir/usr
